apiVersion: apps/v1
kind: Deployment
metadata:
  name: scolastico-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scolastico-app
  template:
    metadata:
      labels:
        app: scolastico-app
    spec:
      containers:
        - name: scolastico-app
          image: scolastico-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: scolastico-app-balancer
spec:
  selector:
    app: scolastico-app
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
